### ISSUE TITLE
Don't modify string prototype

### ISSUE THREAD

**Issue by patrickarlt** [shelljs/shelljs#159] opened 2014-09-08 18:28 UTC
Ran into an issue debugging an issue with a coworker.

If the `string` module is included anywhere downstream of `shelljs` you get a pair of warnings.

```bash
to: wrong arguments

toEnd: wrong arguments
```

Here is the script to duplicate the issue.

```js
var shelljs = require('shelljs');
var S = require('string');

// will produce output...
```

This has already been caught by several other issues...

* https://github.com/jprichardson/string.js/issues/73
* https://github.com/paazmaya/grunt-trimtrailingspaces/issues/1
* https://github.com/admc/wd/issues/220

Since shelljs is so heavily relied upon it might be a better to not modify the global `String` prototype.

**Comment by cookch10** [comment] 2015-03-05 18:51
Also experiencing this issue.  Please fix.

**Comment by steveoh** [comment] 2015-03-26 19:01
[to](https://github.com/arturadib/shelljs/blob/20db182fcbc96cb8bb4ece2c748b15b755b022ba/shell.js#L58)
and [toEnd](
https://github.com/arturadib/shelljs/blob/20db182fcbc96cb8bb4ece2c748b15b755b022ba/shell.js#L62)

prototype violations. This should be fairly simple to fix?

**Comment by jprichardson** [comment] 2015-03-26 19:19
I've published a new version `3.1.1` of `string.js` that should work around this problem.

**Comment by myndzi** [comment] 2015-06-02 17:41
Extending the prototype at all is dubious, especially implicitly instead of explicitly, but doing so with functions that dirty the filesystem is just nasty. I just spent two hours of my day running down where a mysterious file was coming from that's a result of what appears to be nasty behavior on the part of both shelljs AND string.js; either fix will do, but they both need it.

**Comment by nfriedly** [comment] 2015-08-05 18:45
+1 This looks to be the root cause of https://github.com/watson-developer-cloud/nodejs-wrapper/issues/56 / https://github.com/jprichardson/string.js/issues/160

**Comment by az7arul** [comment] 2015-08-05 19:35
version `3.3.1` of `string.js` now ignores the `to` and `toEnd` methods to get around this problem

**Comment by garaboncias** [comment] 2015-10-14 15:00
+1 pleasse do not modify or at least make it not enumerable.

**Comment by nfischer** [comment] 2016-02-20 05:29
Bumping this thread, since this will finally be resolved in #360. Thanks for reporting this!

**Closed** 2016-02-20 22:56 UTC
Labels: high priority

**Comment by nfischer** [comment] 2016-03-19 23:43
> Even an option to disable it would work great. Thanks!

We decided to go with the "opt-out" approach for ShellJS v0.7 (see #398 for the discussion). If you don't mind having the string prototype extended, you can continue to use the convenience script `require('shelljs/global')`. If this is a concern for you, you can use `var shell = require('shelljs')` instead, which neither modifies the prototype nor pollutes the global namespace.

If the string prototype is still a concern for `shelljs/global`, please comment on this thread and we can consider removing that for ShellJS v0.8.

**Comment by BYK** [comment] 2016-03-20 20:46
@nfischer - I think modifying builtins or their prototypes is a very bad idea. I'd encourage deprecating the whole `global` thing for the next version TBH. (and yeah string prototype modification too)

**Comment by ariporad** [comment] 2016-03-20 20:58
@BYK: I think the idea behind global mode is to more closely emulate bash scripting in shelljs. If you're writing a simple script which is only shelljs commands, it can save a lot of time. This is also why we have the non-global option for people who would prefer not to.

**Comment by BYK** [comment] 2016-03-21 12:21
@ariporad - we can still do that with `require` thought right? And with ES6 imports (I know, not ready yet) it is even easier.

Anyways, I think even if we keep the global mode, having our own `String` class and modifying its prototype is way safer than touching a built-in's prototype.

**Comment by nfischer** [comment] 2016-03-21 16:54
The rationale is that modifying the global namespace is equally as wrong as modifying the builtin. So, for now, it's been added back, but only for global. I think we should give a deprecation warning (converting a string to a ShellString is an alternative). This is something I wouldn't be opposed to removing for good in v0.8.
