### ISSUE TITLE
Run second shell script

### ISSUE THREAD

**Issue by oleghalin** [shelljs/shelljs#756] opened 2017-07-27 18:29 UTC
I need to run second script even if first steal running. Now im using this: 
shell.exec('node vexample2.js ',{silent:true});

but if i send second socket message to run next script when this already finished - have and error.

**Comment by nfischer** [comment] 2017-07-28 04:56
Can you post a more detailed description (including minimal scripts)?

**Comment by oleghalin** [comment] 2017-08-01 09:29
Minimal scripts? Im using node

**Comment by nfischer** [comment] 2017-08-04 17:15
Please post the code which produces the issue. It's hard to understand your problem if you don't clearly describe where the problem is.

**Comment by oleghalin** [comment] 2017-08-05 12:20
Its more my mistake, than error. I need to run shell script and continue check socket server. But while script is working socket cant get new messages.
![2017-05-29 14 06 27](https://user-images.githubusercontent.com/9086983/28995419-8feff504-79f1-11e7-9241-632878728839.png)

**Comment by nfischer** [comment] 2017-08-06 20:55
> Its more my mistake, than error.

Sounds like user error, I'm assuming this is not a shelljs bug. Closing.

If this is indeed a shelljs bug, then please post a *minimum code example* (the smallest possible script to reproduce the issue). And please paste it in a [markdown code block](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) (no screenshots or unformatted code please).

**Closed by nfischer** 2017-08-06 20:55 UTC
