### ISSUE TITLE
Force symbolic link (ln -sf) does not overwrite/recreate existing destination

### ISSUE THREAD

**Issue by SeanSnyders** [shelljs/shelljs#830] opened 2018-04-03 02:17 UTC
### Node version (or tell us if you're using electron or some other framework):

8.11.1

### npm version (or tell us if you're using electron or some other framework):

5.6.0

### ShellJS version (the most recent version/Github branch you see the bug on):

0.7.7 and 0.8.1

### Operating system:

ubuntu 14.04

### Description of the bug:

On `ubuntu` the symlink command `ln -sf` seems to not force the link if the destination exists. Seems to work fine on `macOS`.

![image](https://user-images.githubusercontent.com/1384135/38225516-60aac02e-3749-11e8-92bd-7d20f69436bf.png)

### Example ShellJS command to reproduce the error:

On linux:

```javascript
var shell = require('shelljs');
shell.ln('-sf', "source", "link");
```

**Comment by nfischer** [comment] 2018-04-03 03:44
Possibly related to #829?

@SeanSnyders could you give a more complete example? It's not clear what `source` and `link` are supposed to be in your example. If one of those is supposed to be a pre-existing file, could you include the sample code which creates that?

When I run your script, I get:

```
ln: Source file does not exist
```

Which makes sense, because I don't have `source` on my disk.

**Comment by SeanSnyders** [comment] 2018-04-03 04:27
Not sure if it is related to #829 because it works for me on `macOS`.

Yes, `source` and `link` are example folder names. It is not intended to run as-is on your machine.
The `source` being the folder to link to, and `link` being the link you are trying to create (typical `ln` semantics: see `man ln`)
And of course I cannot give you an exact code example as it depends on exact folders being present on your machine as to mine, which is not possible.

The error is as I described when trying to run `shell.ln` with the `dest` parameter a path that is already a **valid** symbolic link. In other words, I am trying to replace my existing symbolic link with a new one thus using the force `-f` flag.

**Comment by nfischer** [comment] 2018-04-03 05:48
> because it works for me on macOS.

I'm not sure what "it" is. What works on macOS? Does that same thing **not** work on Linux or some other OS?

> depends on exact folders being present on your machine as to mine, which is not possible.

Or you could write a script *which creates* those precondition folders/files/symlinks :smile: `ln('-sf', 'source', 'link')` is obviously not clear enough: you're just quoting the docs for how to use `ln()`, not explaining the issue.

I'm happy to investigate the issue, but it helps to have a script I can run in an empty working directory to reproduce the problem (and so that I can compare against unix behavior).

**Comment by nfischer** [comment] 2018-05-10 00:25
> In other words, I am trying to replace my existing symbolic link with a new one thus using the force -f flag.

I tried once more today to repro (on Linux). Specifically:

 * try overwriting a **valid** symlink to a **file** with a symlink (it works)
 * try overwriting a **valid** symlink to a **directory** with a symlink (it works)

I'm closing this because I can't repro. @SeanSnyders please ping this thread if you still see the issue, and if possible, please provide more clarification.

**Closed by nfischer** 2018-05-10 00:25 UTC
