### ISSUE TITLE
Shelljs print stderr to console even if exec-only "silent" is true

### ISSUE THREAD

**Issue by solominsn** [shelljs/shelljs#905] opened 2018-11-12 16:42 UTC
### Node version (or tell us if you're using electron or some other framework):
6.14.x, but it doesn't matter

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.2

### Operating system:
Debian 10

### Description of the bug:
Bug #887 has been closed, but it's a real bug. Exec-only "silent" option is not passed to helper function (common.error) which check error code and write stderr to console. Changing global config "silent" to false is only way to suppress stderr printing. If required fix can be prepared and pushed.

### Example ShellJS command to reproduce the error:

```javascript
shell.exec('npm run invalid-command', { silent: true });
```
Invalid command returns non-zero error code and shelljs print stderr to console.

**Comment by solominsn** [comment] 2018-11-12 16:46
Already fixed in the master, not in npm.

**Comment by koraa** [comment] 2019-01-04 10:32
@solominsn Thanks a lot for fixing this issue!
 I just ran into this…can we have a release please? ^^

**Comment by koraa** [comment] 2019-01-04 10:55
Is there an option on master to keep the current behavior of printing the output only on error?
Something like `{silent: true, printOnError: true}`?

**Comment by nfischer** [comment] 2019-01-05 09:03
> I just ran into this…can we have a release please? ^^

This was fixed in #892 (which made it into v0.8.3. I just updated the [changelog](https://github.com/shelljs/shelljs/blob/master/CHANGELOG.md) to reflect this.

**Comment by nfischer** [comment] 2019-01-05 09:05
> Is there an option on master to keep the current behavior of printing the output only on error?
Something like `{silent: true, printOnError: true}`?

No such option, unfortunately. If you want this behavior only for `exec()`, you could implement it as:

```js
const ret = shell.exec(cmd, { silent: true });
process.stdout.write(ret.stdout);

// or
const c = shell.exec(cmd, {silent: tru

**Comment by nfischer** [comment] 2019-01-09 07:12
Re-closing (I think I reopened accidentally, sorry). Filed the request as #927

**Closed by nfischer** 2019-01-09 07:12 UTC

**Comment by nfischer** [comment] 2019-01-09 07:14
For tracking, this is a duplicate of #851
