### ISSUE TITLE
Update the version of dependency package (glob)

### ISSUE THREAD

**Issue by matthieuLepetit** [shelljs/shelljs#1176] opened 2024-12-05 17:18 UTC
### Node version (or tell us if you're using electron or some other framework):
v22.12.0
### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs@0.8.5
### Operating system:
Windows WSL
### Description of the bug:

When installing the package there is glob package version which is no longer supported.

It produces a warning : 
`npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported`

### command to reproduce the error
```npm
npm install shelljs
```

**Comment by nfischer** [comment] 2024-12-09 20:16
Duplicate of issue https://github.com/shelljs/shelljs/issues/828.

**Closed by nfischer** 2024-12-09 20:16 UTC
