### ISSUE TITLE
node v14: (node:86796) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency

### ISSUE THREAD

**Issue by aladdin-add** [shelljs/shelljs#992] opened 2020-04-26 04:02 UTC
### Node version (or tell us if you're using electron or some other framework):
v14.0.0
### ShellJS version (the most recent version/Github branch you see the bug on):
shelljs@0.8.3
### Operating system:
macos
### Description of the bug:
```bash
(node:86796) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:86796) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:86796) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
```
### Example ShellJS command to reproduce the error:

```javascript

```

**Comment by nfischer** [comment] 2020-04-26 07:14
Dupe of #973. Use ShellJS 0.8.4 please.

**Closed by nfischer** 2020-04-26 07:14 UTC
Labels: duplicate

**Comment by aladdin-add** [comment] 2020-04-26 07:36
thanks for fixing this. btw, did you forget to push the master. (it's still 0.8.3)

**Comment by nfischer** [comment] 2020-04-27 17:48
This was pushed from a release branch, not from master. The fix is already on master.

**Comment by nfischer** [comment] 2020-04-27 17:50
The release branch is here: https://github.com/shelljs/shelljs/tree/0.8-release

You can see the last 2 commits of https://github.com/shelljs/shelljs/commits/0.8-release are verified under my gpg signature.
