### ISSUE TITLE
command exec("something here", {silent: false}) does not output "colored" text

### ISSUE THREAD

**Issue by lockevn** [shelljs/shelljs#186] opened 2015-02-07 06:46 UTC
Hi, I use exec() to run build script (MsBuild on Windows). It runs fine, except one thing that it ignore colored text output by MsBuild. It leads to warning and error text is bypassed and is hard to recognize.

Example for reproducing:

```
echo('old color');
exec('color 8f');
echo('new color');
exit();
```

Could you please check it? Thank you.

**Comment by stoeffel** [comment] 2015-04-08 04:07
same here on osx

**Comment by victorwpbastos** [comment] 2015-06-11 17:52
same here on windows 7.

**Comment by ariporad** [comment] 2016-01-24 19:54
Yeah, that's because commands don't output the color bits when the output is piped. (It would look really weird).

If someone wants to look into it, I think there's a way to bypass it, but it's not super high priority.

**Comment by nfischer** [comment] 2018-07-12 01:07
Duplicate of #86

**Closed by nfischer** 2018-07-12 01:07 UTC
Labels: exec, low priority
