### ISSUE TITLE
return using exec() with non-returning shell command

### ISSUE THREAD

**Issue by multivoltage** [shelljs/shelljs#696] opened 2017-03-26 22:41 UTC
### Node version (or tell us if you're using electron or some other framework):
7.3.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7
### Operating system:
Manjaro linux 
### Description of the bug:
I have to run tor command that does not return value, like 'tor'.
### Example ShellJS command to reproduce the error:

```javascript
  if (shell.exec('tor').code !== 0) {
    console.log('cannot run tor command');
    console.log(this);
    shell.exit(1);
    return false;
  }
  return true;

```
I can read a false value only if there is an error. if tor (or other equivalent command) will work great, I cannot have a signal

**Comment by nfischer** [comment] 2017-03-29 03:51
I don't see what the bug is. Why can't you run your command?

I can't help if there's a bug with the `tor` command, we don't support that.

**Comment by nfischer** [comment] 2017-03-30 21:19
@multivoltage I don't see what the issue is, so I'm closing this. Please reopen or ping this thread if I'm missing something.

**Closed by nfischer** 2017-03-30 21:19 UTC

**Comment by multivoltage** [comment] 2017-03-30 22:31
Tor is bot the problem. It was only an example. 
I mean alla commando that dont have a return. Try to think a simple http server with node. When I run my simple script node listen on port xxx for infinite time. So .exec() return only if I generate an ezceotion inside my node server.

**Comment by freitagbr** [comment] 2017-03-31 03:16
Well, this is the way `.exec` is intended to work. It only returns after the child process exits. So, if you are running a long-running process, like a web server, then `.exec` will block the entire time the process is running.

If you need to start a process, but you want to be able to run other code while that process is running, a better choice would be [`child_process.spawn`](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options) or [`child_process.execFile`](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) from the node core `'child_process'` module.

**Comment by nfischer** [comment] 2017-03-31 03:34
If you want `exec()` to be asynchronous, you need to use it in asynchronous mode:

```js
shell.exec(... {async: true}); // launches a command and returns immediately
```

@freitagbr's other suggestions are also good alternatives.

**Comment by multivoltage** [comment] 2017-03-31 06:07
Thanks everyone. The only way I can find is To parse stdout and checking for string Luke "server run on port8080" or also "tor done 100%".

Thanks
