### ISSUE TITLE
[bug] `echo(content).to(file)` also sends `content` to stdout

### ISSUE THREAD

**Issue by MisterTicot** [shelljs/shelljs#958] opened 2019-08-09 05:17 UTC
### Node version (or tell us if you're using electron or some other framework):
v10.15.2

### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.3

### Operating system:
Ubuntu 19.04

### Description of the bug:

`echo(content).to(file)` also sends `content` to stdout. If `.to(file)` is meant to act like `>`, then it should capture the output rather than copy it to file (like `tee` would do).

### Example ShellJS command to reproduce the error:

```javascript
shell.echo("foo").to("bar")
```

**Comment by nfischer** [comment] 2019-08-13 06:50
This is a duplicate of issue #146; my hope was that #800 would address this elegantly, but we've made no progress on that issue. Nonetheless, closing this as a duplicate.

**Closed by nfischer** 2019-08-13 06:50 UTC
Labels: duplicate
