### ISSUE TITLE
exec doesnt seem to be working

### ISSUE THREAD

**Issue by jeremyrajan** [shelljs/shelljs#480] opened 2016-07-24 09:20 UTC
### Node version:

6.2.0
### ShellJS version

0.7.0
### Operating system:

Mac
### Description of the bug:

I am trying to run the following command (that I copied from docs) in my electron console.

![image](https://cloud.githubusercontent.com/assets/2890683/17082963/b3d787e2-51ad-11e6-8399-490ae148b18d.png)

Any idea, why this would be having. As I want to return the version number for checks. Other commands such as `which` are working but just `exec`

Thank you! :)

**Comment by nfischer** [comment] 2016-07-24 15:11
@ariporad can you reproduce this? This seems to be related to #471, and seems to be Mac-specific

**Comment by ariporad** [comment] 2016-07-24 18:41
@jeremyrajan: Can you expand the error messages to see the full stacks? Thanks!

**Comment by jeremyrajan** [comment] 2016-07-29 04:09
Hi @ariporad , apologies for delay. Following is the full stack trace:

```javascript
exec('node --version', {silent:true})

/Users/DextorG/Documents/Projects/Github/installer_app/node_modules/shelljs/src/com…:40 

exec: internal errorlog @ /Users/DextorG/Documents/Projects/Github/installer_app/node_modules/shelljs/src/com…:40

error @ /Users/DextorG/Documents/Projects/Github/installer_app/node_modules/shelljs/src/com…:68

_exec @ /Users/DextorG/Documents/Projects/Github/installer_app/node_modules/shelljs/src/exe…:256

(anonymous function) @ /Users/DextorG/Documents/Projects/Github/installer_app/node_modules/shelljs/src/com…:269

(anonymous function) @ VM345:1
```

Thank you :)

**Comment by jeremyrajan** [comment] 2016-08-02 07:41
Any idea guys? :). Neither of the exec commands are working for me

**Comment by nfischer** [comment] 2016-08-02 19:01
The only workaround I know might be `process.version` for the version. Doesn't fix this issue though.

**Comment by ariporad** [comment] 2016-08-04 04:47
Hmm...

We do seem to have a lot of problems with electron, don't we?

@jeremyrajan: Will you try this with the `fix/480` branch, and let me know what the output is? Thanks.

**Comment by giacgbj** [comment] 2016-08-05 08:16
@ariporad Do you need any further information?

Mac OS X 10.11.6

e.message
```
"Command failed: "/path/to/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper" "/var/folders/p2/v0630kzj4lb8v65d325zn5vh0000gn/T/shelljs_a4b21fa8414ec26b6caf""
```

e.stack
```
"Error: Command failed: "/path/to/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper" "/var/folders/p2/v0630kzj4lb8v65d325zn5vh0000gn/T/shelljs_a4b21fa8414ec26b6caf"
    at checkExecSyncError (child_process.js:487:13)
    at Object.execSync (child_process.js:527:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:678:28)
    at execSync (/path/to/app/app/node_modules/shelljs/src/exec.js:106:13)
    at Object._exec (/path/to/app/app/node_modules/shelljs/src/exec.js:264:14)
    at Object.exec (/path/to/app/app/node_modules/shelljs/src/common.js:275:23)
    at file:///path/to/app/app/index.html:14:15
```

**Comment by ariporad** [comment] 2016-08-05 19:36
Ohh... I think I know the problem: I think Electron is breaking `process.execPath`. I'll look into this a bit more.

**Comment by ariporad** [comment] 2016-08-05 20:24
@giacgbj: So, it would appear that the node binary is built in to the electron executable, and as such we can't run it individually. This is problematic, and I'm really not sure how we can work around it.

**Comment by nfischer** [comment] 2016-08-05 22:20
@ariporad Suggestion:

```js
var nodePath = isValid(process.execPath) ? process.execPath
             : (which('node') || which('nodejs'));
if (!nodePath)
  throw new Error('Unable to find path to NodeJS executable');
```

Check the semantics of `which()` to make sure this will work.

**Comment by ariporad** [comment] 2016-08-05 22:57
@nfischer: I'm not really sure what `isValid` would do. Theoretically, it should be totally valid to do:

```bash
mv /usr/bin/node /usr/bin/myNodeJSWithAFunnyName
myNodeJSWithAFunnyName script.js
```

**Comment by nfischer** [comment] 2016-08-05 23:11
Yes, that's the rationale behind using `process.execPath`. But you said `execPath` doesn't work, due to it being part of electron.

Just test if `execPath` points to something that is part of electron, then fallback to a name we know node usually goes by. If `process.execPath` doesn't work, and neither do any of the usually names for the node binary, then we can throw an error. It won't handle every case, but wouldn't it fix this issue?

**Comment by ariporad** [comment] 2016-08-06 18:59
@nfischer: There would be no way to test if it's part of electron. For example, Slack is written with Electron. From Slack's perspective, `process.execPath` is `/Applications/Slack.app/Contents/MacOS/Slack`. Atom is also written with slack. From Atom's perspective, `process.execPath` is `/Applications/Atom.app/Contents/MacOS/Atom`. So, I'm not sure how we would detect this.

I don't think we could just test if the path ends in `node`, because that would break for `iojs`, (or if there are symlinks).

We could have a `shell.config.electron`, which feels messy. Or, we could not support electron, which I don't like. Or, we could try to detect electron and do something special based on it. (Maybe we could submit a PR to electron which adds a `-e` option?).

Another thing is that Electron apps are frequently non-developer facing, so it might be bad to require people to have a seperate node instance on their machines.

**Comment by ariporad** [comment] 2016-08-08 20:30
Hmm... @giacgbj, Good point. @jeremyrajan?

**Comment by jeremyrajan** [comment] 2016-08-09 04:39
hmm, that works too but is it cross platform compatible because I believe normally we have to execute a bat file for WIN? Or am i totally wrong :)

**Comment by nfischer** [comment] 2016-08-09 04:54
@jeremyrajan 

```js
var ret = child_process.execSync('node --version');
```

What's the issue with Windows?

**Comment by nfischer** [comment] 2017-01-09 03:08
Closing this because we've documented a workaround [on the wiki](https://github.com/shelljs/shelljs/wiki/Electron-compatibility). Please comment if this workaround is insufficient.

**Closed by nfischer** 2017-01-09 03:08 UTC
Labels: electron

**Comment by HardikDG** [comment] 2017-08-06 05:11
As per wiki I need to set 'config.execPath', How can I specify that? Any sample example for it?

**Comment by nfischer** [comment] 2017-08-06 20:47
@HardikDG please see the wiki, it explains how you might find the path to your node binary...

**Comment by HardikDG** [comment] 2017-08-07 05:56
@nfischer I already saw the wiki, from the wiki itself I come to this post, I got the path to the node in my system. 
My question is where I need to set this path? it says 'set config.execPath' but where? In my JS file or in my system where? 
Can you please show the command/code to set this path 

Sorry if it's very stupid question but I don't have deep knowledge of NodeJS, so I don't have that idea.

**Comment by nfischer** [comment] 2017-08-08 01:45
Set it like any regular variable.

```js
// This is inside your javascript file
var shell = require('shelljs');
shell.config.execPath = 'path/to/node/binary'; // Replace this with the real path

// The rest of your script...
```

**Comment by HardikDG** [comment] 2017-08-08 04:44
@nfischer  Thanks. It worked in my electron app.

**Comment by gayanai** [comment] 2018-05-10 01:48
@nfischer  Hi, glad to see there is  a workaround. This got failed throwing an error
```
        var shell = require('shelljs');
        let nodePath = (shell.which('node').toString());
        shell.config.execPath = nodePath;
        shell.exec('git');
```
May I know is there a compatible library version to make this work? Thank you

**Comment by nfischer** [comment] 2018-05-10 06:58
@gayanai does that workaround not work for you? This is still hit-or-miss, and we don't guarantee that workaround (otherwise, we would bake it into shelljs core).

**Comment by nfischer** [comment] 2018-05-10 20:55
@gayanai well, where is your path to `node`? For example, run this in the terminal:

```sh
$ which node || which nodejs # does this point to something?
```

Whatever that points to should be your `execPath` value. This is a best-effort kind of thing. If you don't have a standalone installation of `node` outside of electron, you'll need to install one for `exec()` to work.

**Comment by gayanai** [comment] 2018-05-10 20:58
@nfischer Hi 
 The path is `/usr/local/bin/node` and I have referred to that path

**Comment by nfischer** [comment] 2018-05-10 22:18
@gayanai if that doesn't fix the issue, then you'll need to provide full error output

**Comment by hazim-j** [comment] 2018-06-27 15:37
setting exec to async seems to work.
```
let command = shell.exec('command', {silent:true, async:true});
command.stdout.on('data', (data) => {
    /* ... do something with data ... */
});
command.stdout.on('finish', (data) => {
    /* ... do something when finished ... */
});
```

**Comment by nfischer** [comment] 2018-06-28 21:15
@hazim-j yes, that is another valid workaround (assuming async works for your use-case). Now that we have async/await in some versions of node, maybe this is a better workaround.

**Comment by nanjixiong218** [comment] 2018-08-28 10:10
node: 10.9.0

electron: 2.0.6

shelljs: 0.8.2

I have set the shell.config.execPath: 

```
import shell from 'shelljs';
shell.config.execPath = '/Users/xuhuiyuan/.nvm/versions/node/v10.9.0/bin/node';
```

but it product another problem:

![image](https://user-images.githubusercontent.com/5085933/44716511-1c166180-aaed-11e8-94d5-03671cd879b0.png)

**Comment by nfischer** [comment] 2018-09-10 18:38
@nanjixiong218 thanks for reporting. Yes, it seems this isn't quite working. I'm not sure what that file (`shelljs_22ff...`) is supposed to be, so I'm not sure what options to recommend.

**Comment by DrakeXiang** [comment] 2018-12-28 10:00
`shell.witch('node')` is null after package with electron-forge, then I used `child_process` instead

**Comment by tracker1** [comment] 2018-12-28 11:14
Forgive my ignorance... If you're bundling the app, couldn't you create an npm dependency to node@compatible-version and reference that?

**Comment by nfischer** [comment] 2018-12-28 20:57
> If you're bundling the app, couldn't you create an npm dependency to node@compatible-version and reference that?

If you're requesting that ShellJS bundle `node` as a dependency, that would blow up our module's size. If you're recommending this for authors of electron apps, then this might be reasonable? I don't know enough about electron to comment, but it otherwise seems like it would satisfy ShellJS's requirements.

**Comment by zxc23** [comment] 2019-08-25 14:57
Thanks to hazim-j above, I got shelljs working within electron like this:

```
import shell from 'shelljs';

function runCommand(command, timeout) {
  return new Promise((resolve, reject) => {
    if (timeout)
      setTimeout(() => {
        reject(new Error('Command timed out'));
      }, timeout);

    shell
      .exec(command, {
        async: true,
        silent: true
      })
      .stdout.on('data', data => {
        resolve(data);
      });
  });
}
```
