### ISSUE TITLE
Outdated dependencies: inflight, glob

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [shelljs/shelljs#1175] opened 2024-10-22 15:47 UTC
### Description of the bug:

Right now, `shelljs@0.8.5` has dependencies on `glob@7.2.3` and `inflight@1.0.6`. Both are deprecated. So whenever you install `shelljs`, you get the following noise in the console:

```plaintext
npm i shelljs
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
```

Would you accept PRs migrating to newer versions of the packages?

I also see that `shelljs` hasn't had a release in a few years. Are there any plans to release a new version?

### Example ~~ShellJS~~ install to reproduce the error:

```shell
npm i shelljs
```

**Comment by nfischer** [comment] 2024-10-27 00:48
Duplicate of issue #828.

Work is in progress on this. You can disregard the warning about memory leaks: yes it is true that `inflight` has a memory leak bug, however ShellJS does not actually use the codepath which calls into `inflight` so we're unaffected by the bug.

**Closed by nfischer** 2024-10-27 00:48 UTC
Labels: duplicate
