### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by ps06756** [shelljs/shelljs#471] opened 2016-07-04 09:33 UTC
### Node version:
4.4.4
### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.0
### Operating system:
OSX 10.11.5 El Captain
### Description of the bug:
Typerror while using shell.exec
### Example ShellJS command to reproduce the error:
java -jar CMDRunner.jar --tool Reporter --generate-png test.png --input-jtl results.jtl --plugin-type ResponseTimesOverTime --width 800 --height 600

I cannot find a simple command which reproduces the above issue, I am attaching a screenshot of the error message I am getting. 

![shelljs_bug](https://cloud.githubusercontent.com/assets/6458027/16556561/61ba0d82-41f8-11e6-9ab0-981b96453985.png)

```javascript

```

**Comment by ariporad** [comment] 2016-07-05 22:39
Hmm... This is really quite strange...

@ps06756, would it be possible for you to share the `.jar` file with us? (Or does this happen with other `.jar`'s?) I'm somewhat at a loss for what's happening.

**Comment by ps06756** [comment] 2016-07-06 03:54
I am using the following jar. 
[CMDRunner.jar.zip](https://github.com/shelljs/shelljs/files/349017/CMDRunner.jar.zip)

If I run the same command, from a terminal then the command runs without any problem.

**Comment by nfischer** [comment] 2016-07-20 21:40
@ariporad Are you still looking into this?

**Comment by nfischer** [comment] 2016-07-31 20:06
I saw a [related error on an OS X Travis worker](https://travis-ci.org/shelljs/shelljs/jobs/148545851). Here's a screenshot, in case the build restarts and wipes out this log:

![screenshot from 2016-07-31 13-02-49](https://cloud.githubusercontent.com/assets/5801521/17279002/68500c5a-571f-11e6-9285-c17da04b563f.png)

**Comment by ariporad** [comment] 2016-08-01 18:21
@nfischer: I think that's related to `shjs`, which is in need of some help, ref #497.

**Comment by ariporad** [comment] 2016-08-01 18:31
@ps06756: Sorry for the delay, I've been really busy recently.

Could you try this with the `#471` branch? I've added some debugging stuff which should hopefully be helpful.

**Comment by nfischer** [comment] 2016-08-01 23:35
> @nfischer: I think that's related to shjs, which is in need of some help, ref #497.

Yes, that's the PR in which the error occurred. I posted it, not to suggest that it's occurring on master branch, but as an example of the error to help with debugging this issue, since neither you nor I have seen the bug pop up in our usage of ShellJS.

**Comment by ariporad** [comment] 2016-08-04 04:42
What?

**Comment by eisenbergrobin** [comment] 2016-08-04 08:28
I'm getting this issue pretty frequently when running a development server with `webpack`: 

```
  [491] ./~/moment/locale/lt.js/private/var/folders/ll/pd5zlkb138ldyyq6mzz9zd8h0000gn/T/shelljs_b5a18701642053f3a4d2:4
  fs.writeFileSync("/var/folders/ll/pd5zlkb138ldyyq6mzz9zd8h0000gn/T/shelljs_0cf1d4941d3414207791", err ? err.code.toString() : '0');
                                                                                                                  ^

TypeError: Cannot read property 'toString' of undefined
    at /private/var/folders/ll/pd5zlkb138ldyyq6mzz9zd8h0000gn/T/shelljs_b5a18701642053f3a4d2:4:115
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
exec: internal error
/script/lib/common.js:40
  if (res.code !== 0) {
         ^

TypeError: Cannot read property 'code' of null
```

On MacOS X 10.11.6 (El Capitan), Node 4.3.2. 

I reproduce this at least twice a day. @ariporad Would you like me to try something to help out with debugging? I can run the `#470` branch if you need.

**Comment by ariporad** [comment] 2016-08-04 16:34
@eisenbergrobin: Sure, if you wouldn't mind trying out the `debug/471` branch, that would rock. I think (_think_) it should be a bit more verbose.

**Comment by eisenbergrobin** [comment] 2016-08-05 08:08
@ariporad: 

Tried putting your `debug/471` branch, unfortunately it seems the code is not valid: 

You are missing a trailing comma [here](https://github.com/shelljs/shelljs/commit/126457ffcc493fe285ea218f8fd949fa9ea8a093#diff-c3bfabb5e6987aa21bc75ffd95a162d6R78) and [here](https://github.com/shelljs/shelljs/commit/126457ffcc493fe285ea218f8fd949fa9ea8a093#diff-c3bfabb5e6987aa21bc75ffd95a162d6R123). 

I fixed it locally, but you might want to fix it on your branch :)

So I'm now running this, I'll get back to you if I get any interesting debug information.

**Comment by ariporad** [comment] 2016-08-05 19:33
@eisenbergrobin: Continually proving my geinousnessness. 😄

**Comment by eisenbergrobin** [comment] 2016-08-08 08:44
@ariporad:

Reproduced it. Here is the extra information from your `console.log`: 

```
[Error: stdout maxBuffer exceeded] cmd: '/bin/sh -c npm run start'
```

So it seems I am exceeding the max `stdout` output buffer... 
I've reduced logging verbosity on my `webpack-dev-middleware` and that should mitigate the problem enough for me not to see it (fingers crossed).

Thanks for the help :)

**Comment by eisenbergrobin** [comment] 2016-08-09 07:31
For those of you having the same issue when running a development server under `webpack-dev-middleware`, this occurs because the command is outputting (after a while) more than what the buffer can handle in a single command. 

I fixed it by making my middleware less verbose when rebuilding: 

```

app.use(require('webpack-dev-middleware')(compiler, {
  noInfo: true,
  stats: {
    colors: true,
    assets: false,
    version: false,
    hash: false,
    timings: false,
    chunks: false,
    chunkModules: false,
  },
}));
```

That means less lines are printed, and I still get information on whether the build was successful and what went wrong.

**Comment by ariporad** [comment] 2016-08-10 14:51
@eisenbergrobin: Have you tried changing the maxBuffer?

**Comment by eisenbergrobin** [comment] 2016-08-10 15:25
@ariporad: Continually proving **my** geniusness 😄 . I had no idea I could pass options from node::child_process to shelljs::exec to handle this. 

I haven't reproduced the issue since the fix described above (since my webpack output was way too verbose anyways), but I increased the buffer size in any case: 

```
const options = {
    ...opts,
    maxBuffer: 1024 * 1000, // Increase maxBuffer on node exec for long-running 'watch' commands with a lot of output to stdout
  };
return shell.exec(cmd, options);
```

Thanks for your help :)

**Comment by nfischer** [comment] 2016-08-10 22:50
Sounds like the root cause of this issue has been solved, so I'll go ahead and close this. Please ping this thread if the `toString` issues occur for some other reason.

**Closed by nfischer** 2016-08-10 22:50 UTC
