### ISSUE TITLE
Getting error cd: not a directory: event if folder exist.

### ISSUE THREAD

**Issue by sw-dev-code** [shelljs/shelljs#1028] opened 2021-04-22 22:50 UTC
Hi,

On Ubuntu 18.04 sometimes when I use the `shell.cd` I'm getting the `cd: not a directory:`  even if that folder exists and the path is in the right place. When I restart the app without any changes `shell.cd` command work without problem.

Whan can be the reason for this kind of unexpected behavior?

**Comment by nfischer** [comment] 2021-04-30 00:01
Do you have a repro case? I would need to know node version, ShellJS version, etc (everything in the issue template).

**Comment by sw-dev-code** [comment] 2021-05-01 08:04
Unfortunately, I don't have a repro case.

Node version: v12.22.0
ShellJS version: v0.8.4
Operating system: Ubuntu 18.04.5 LTS

ShellJS command which create a problem:

`shell.cd('/opt/projects');
`

Every command after this one is going to return the same error.

**Comment by nfischer** [comment] 2021-06-02 23:34
I cannot repro. I'm on Ubuntu 20.04, node v12.22.0, shelljs v0.8.4.

```
$ cat repro.js
var shell = require('shelljs');

shell.cd('/opt/projects');
console.log(shell.ls());

$ node repro.js
cd: no such file or directory: /opt/projects
[
  'node_modules',
  'package-lock.json',
  'repro.js',
  stdout: 'node_modules\npackage-lock.json\nrepro.js\n',
  stderr: null,
  code: 0,
  cat: [Function: bound ],
  exec: [Function: bound ],
  grep: [Function: bound ],
  head: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  uniq: [Function: bound ]
]
```

I only get the error message when I run the `cd()` command (and that's because the folder doesn't exist). I don't get the error message for subsequent commands. I'm going to close this because it's not reproducible, but please attach a minimal JS script if you can still repro.

**Closed by nfischer** 2021-06-02 23:34 UTC
Labels: needs feedback, not reproducible
