### ISSUE TITLE
There's no simple way to hide stderr, like the "silent" option for exec

### ISSUE THREAD

**Issue by Sushisource** [shelljs/shelljs#898] opened 2018-11-05 22:20 UTC
This is a feature request rather than a bug -- right now (as of 0.8.2) with `exec` you can pass `silent: true`, but it only suppresses stdout, which makes sense.

However, it would be good to have a simple way to suppress *all* output, which isn't easy to do as it stands. A `silentErr` option would make this easy.

Thanks!

**Comment by nfischer** [comment] 2018-11-06 09:45
Looks like a duplicate of #851?

**Comment by nfischer** [comment] 2018-11-06 09:46
Release isn't out yet, but since this is a bug, it'll be in a patch release.

**Closed by nfischer** 2018-11-06 09:45 UTC
