### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by eGavr** [shelljs/shelljs#158] opened 2014-08-31 14:51 UTC
I've `exec`ed the shell script in a loop for a few time and after some iterations I've received this error:

```bash
shell.js: internal error
Error: spawn EMFILE
    at errnoException (child_process.js:980:11)
    at ChildProcess.spawn (child_process.js:927:11)
    at exports.spawn (child_process.js:715:9)
    at Object.exports.execFile (child_process.js:607:15)
    at Object.exports.exec (child_process.js:578:18)
```

Can you help me? What is it?

**Comment by ariporad** [comment] 2016-01-24 20:10
@eGavr, @lo1tuma: Would one of you mind testing it with the latest version of shelljs? Thanks!

**Comment by nfischer** [comment] 2016-01-24 20:36
It sounds like this is opening too many files, which doesn't sound like a shelljs-specific issue. Perhaps @eGavr should modify the shell script? Or perhaps the issue lies somewhere else.

**Comment by nfischer** [comment] 2016-07-25 06:36
I'm going to go ahead and close this, since it doesn't sound like it's specifically caused by ShellJS. Please reopen if the issue comes back.

**Closed by nfischer** 2016-07-25 06:36 UTC
Labels: blocked

**Comment by GroovyQA** [comment] 2017-02-23 18:52
I had the same issue and turns out it was my Path and environment variables messed up. Executing the same command manually gave me the clue.
