### ISSUE TITLE
'ln -s ./node_modules/@angular/material ./styles/aio' not working

### ISSUE THREAD

**Issue by tngx99** [shelljs/shelljs#1001] opened 2020-07-22 01:44 UTC
### Example ShellJS command to reproduce the error:

```javascript
ln -s ./node_modules/@angular/material ./styles/aio
```

Check the source file `ln.js` line 49:

```
var resolvedSourcePath = isAbsolute ? sourcePath : path.resolve(process.cwd(), path.dirname(dest), source);
```

It should be:

```
var resolvedSourcePath = isAbsolute ? sourcePath : path.resolve(process.cwd(), source);
```

**Comment by nfischer** [comment] 2020-07-28 07:16
Can you describe the expected and observed behavior in more detail? ShellJS appears to be working as intended to me.

> ```js
> ln -s ./node_modules/@angular/material ./styles/aio
> ```

`ln -s` is very tricky to wield correctly. Your command creates a symlink `styles/aio` which points (relative to its own path, not your working directory) to `node_modules/@angular/material`. This is often surprising since it's not how `cp`, `mv`, etc. behave (those accept a path relative to the working directory, not relative to the destination file's path).

Of course, if you **do have** a file at `./styles/node_modules/@angular/material` then you did the right thing (and you'll see `shx ln` and unix `ln` behave similarly). But that doesn't seem to be what you suggested in your code snippet. I'm tentatively closing this ticket, but please let me know if I've misunderstood.

**Closed by nfischer** 2020-07-28 07:16 UTC
Labels: question, wontfix
