### ISSUE TITLE
Invalid version number (0.0.1alpha1)

### ISSUE THREAD

**Issue by omidgolparvar** [shelljs/shelljs#399] opened 2016-03-18 16:05 UTC
When I use npm to update my packages, it fails and in the `npm-debug.log` file, and in terminal, it show :
`Invalid Version: 0.0.1alpha1`
I search that version number in all json files in `~/.npm/` folder, and it has only ONE result :
`$ grep -lr "0.0.1alpha1" *`
`skimdb.npmjs.com/registry/shelljs/.cache.json`
I think the problem is `shelljs` json file.

**Comment by nfischer** [comment] 2016-03-18 16:51
Duplicate of #390 

@omidgolparvar I'm unable to reproduce this, and I believe we unpublished the versions in question. Could you please post the output of `$ npm view shelljs versions`? Thanks!

**Comment by nfischer** [comment] 2016-03-18 17:22
@omidgolparvar Which npm registry are you using? I can only reproduce this when I switch to the mirror at `https://skimdb.npmjs.com/registry`. When I use `npm config set registry https://registry.npmjs.org/`, there are no issues.

**Comment by omidgolparvar** [comment] 2016-03-18 17:58
@nfischer This is out of ` $ npm view shelljs versions ` :
`
[ '0.0.1alpha1',
  '0.0.1',
  '0.0.2pre1',
  '0.0.2',
  '0.0.3',
  '0.0.4pre1',
  '0.0.4',
  '0.0.5pre1',
  '0.0.5pre2',
  '0.0.5pre3',
  '0.0.5pre4',
  '0.0.5',
  '0.0.6pre1',
  '0.0.6pre2',
  '0.0.6',
  '0.0.7',
  '0.0.8',
  '0.0.9',
  '0.1.0',
  '0.1.1',
  '0.1.2',
  '0.1.3',
  '0.1.4',
  '0.2.0',
  '0.2.1',
  '0.2.2',
  '0.2.3',
  '0.2.4',
  '0.2.5',
  '0.2.6',
  '0.3.0',
  '0.4.0',
  '0.5.0',
  '0.5.1',
  '0.5.2',
  '0.5.3',
  '0.6.0' ]
`
and currently use this registry : `registry = "http://skimdb.npmjs.com/registry/"` . If I change my config with `npm config set registry https://registry.npmjs.org/` , my problem will be solved?

**Comment by nfischer** [comment] 2016-03-18 18:44
@omidgolparver I believe that should fix the issue for you. As it stands, I can't modify the published packages on the other registry (perhaps @ariporad can?).

**Comment by omidgolparvar** [comment] 2016-03-18 19:13
@nfischer Thanks for your help. Setting new config helped and works.

**Comment by nfischer** [comment] 2016-03-18 19:39
Awesome! I'm going to close this issue then. I'll see what we can do about modifying that registry, as well.

**Closed** 2016-03-18 19:39 UTC

**Comment by ariporad** [comment] 2016-03-19 23:17
I've got no clue about the other registry, sorry.


Ari
