### ISSUE TITLE
shelljs.exec hangs when password it's asked

### ISSUE THREAD

**Issue by napcat** [shelljs/shelljs#716] opened 2017-05-03 16:29 UTC
### Node version (or tell us if you're using electron or some other framework):
v6.10.2

### ShellJS version (the most recent version/Github branch you see the bug on):
Most recent: 0.7.7

### Operating system:
Windows 10

### Description of the bug:
I have a node js script and I'm trying to exec a command to get some facebook hash keys.
When the command runs it needs the user to input the password, but the script hangs and stop runnning. The password action does not show any chars that are being written.

### Example ShellJS command to reproduce the error:

```
var path          = require('path');
var os              = require('os');

var homedir = os.homedir();

var command = 'keytool -exportcert -alias androiddebugkey -keystore ' 
+ path.join(homedir, '\\.android\\debug.keystore') 
+ ' | openssl sha1 -binary | openssl base64';

shelljs.exec(command);
```

**Comment by nfischer** [comment] 2017-05-03 20:16
We don't support interactive programs with `exec()`. This will hopefully be addressed in an alternative to exec.

**Comment by protoEvangelion** [comment] 2017-10-17 18:28
@nfischer Are there any updates or workarounds for this?

**Comment by nfischer** [comment] 2017-10-17 22:17
I'll write a FAQ for interactive programs.

**Comment by protoEvangelion** [comment] 2017-10-17 23:11
Thanks @nfischer.

Idk if this would be helpful, but I was able to get it to work using the ['exec-sh' package](https://www.npmjs.com/package/exec-sh) just by doing: `execSh(myCmd)`

Maybe their implementation would help :)

**Comment by nfischer** [comment] 2017-10-18 01:59
Workaround is in the FAQs: https://github.com/shelljs/shelljs/wiki/FAQ#running-interactive-programs-with-exec

Let me know if this doesn't work.

Duplicate of #424.

**Comment by nfischer** [comment] 2017-10-18 02:01
Duplicate of #424

**Closed by nfischer** 2017-10-18 02:01 UTC
Labels: exec
