### ISSUE TITLE
Difference between bash ls -R and ShellJS ls -R with symlinks

### ISSUE THREAD

**Issue by frandiox** [shelljs/shelljs#666] opened 2017-02-24 06:26 UTC
### Node version (or tell us if you're using electron or some other framework):
Node 7.1.0

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.6

### Operating system:
Arch Linux 64-bit + bash/zsh

### Description of the bug:
![shelljs-lsr](https://cloud.githubusercontent.com/assets/1634092/23292649/92b12604-faa4-11e6-95e0-cb0e76d90ec3.png)

The output of a normal `ls -R` (bash) is different from ShellJS' `ls -R`. I have created a symlink to `a_dir` directory called `a_dir-link`. Bash does not follow that symlink with `ls -R`, it just shows a symlink entry. However, ShellJS follows that link only 1 level. I think the two highlighted lines on the left side should not appear.

### Example ShellJS command to reproduce the error:

```javascript
ls -R
```

**Comment by nfischer** [comment] 2017-02-24 19:04
@frankdiox thanks for reporting. This looks like a bug.

For posterity, here's a set of minimal steps to reproduce:

```sh
$ mkdir foo && cd foo/
$ mkdir a_dir/
$ ln -s a_dir/ a_dir-link
$ touch a_dir/should-see-only-once
$ ls -R . # regular ls does not recurse into links
.:
a_dir  a_dir-link

./a_dir:
should-see-only-once
$ shx ls -R . # shelljs v0.7.6 does recurse
a_dir
a_dir-link
a_dir-link/should-see-only-once
a_dir/should-see-only-once

$ ls -RL . # regular ls with the -L option does recurse
.:
a_dir  a_dir-link

./a_dir:
should-see-only-once

./a_dir-link:
should-see-only-once
```

This is tricky, however, since this code should also work:

```sh
$ ls -R a_dir-link/ # if invoked directly on a link, we do descend into the link
should-see-only-once
```

@frankdiox would you be able to write up some tests and a fix for this?

**Closed** 2017-03-01 01:32 UTC
