### ISSUE TITLE
Uncaught TypeError: Cannot read property 'electron' of undefined

### ISSUE THREAD

**Issue by 861621821** [shelljs/shelljs#1041] opened 2021-08-12 10:13 UTC
### Node version (or tell us if you're using electron or some other framework):
v14.16.0
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Example ShellJS command to reproduce the error:

```javascript
common.js?bd9a:15 Uncaught TypeError: Cannot read property 'electron' of undefined
    at Object.eval (common.js?bd9a:15)
    at eval (common.js:470)
    at Object../node_modules/shelljs/src/common.js (chunk-vendors.js:6084)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at Object.eval (shell.js?0ff4:9)
    at eval (shell.js:158)
    at Object../node_modules/shelljs/shell.js (chunk-vendors.js:6039)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
```

**Comment by tiantud** [comment] 2021-08-24 20:39
I'm facing the same error as you do.

What I am trying to do is to create a electron app with vue and just run it with `npm run electron:serve`.
The app should execute some command when a button is clicked. 

---

I think the problem is: A browser cannot execute command. It handles only http(s) connections. 
If you are trying to execute shelljs in a browser-page, or a browser-based-app, then comes this error.

---

Here is my solution to execute some command without shelljs/child_process (shelljs uses child_process): 

- Create a simple http server with express. It is started with `node xxxx.js` and use shelljs/child_process to execute the command comes from request. (works fine)
- My electron-app send http request to this local server.

---

Here is my index.js to start a "simple http server": 

```
var express = require("express");
var exec = require("child_process").exec;
var app = express();


app.listen(3000, () => {
 console.log("Server running on port 3000");
});

app.get("/exec", (req, res, next) => {
 var cmd = req.query.cmd;
 exec(cmd.toString().replace('$', ' '));
});
```

Quick start: `(sudo) node index.js`

URL: `http://localhost:3000/exec?cmd=reboot$now`

The $ will be replaced by space, you can also use URL encoding.

---

A dirty solution, yes. But it works.

**Comment by nfischer** [comment] 2021-11-29 02:49
Interesting. It sounds like electron removed `process.versions` (we try to detect electron by checking `process.versions.electron`). Electron claims this should exist though, so maybe this is an electron bug?

https://www.electronjs.org/docs/latest/api/process#processversionselectron-readonly

Let me know if there's a better way to detect electron, otherwise I'm going to mark this as wontfix.

**Closed by nfischer** 2021-11-29 02:49 UTC
