### ISSUE TITLE
Getting "ENOENT: no such file or directory ... AppData/Local/Temp/shelljs_xxxxx" when using shell.exec( )

### ISSUE THREAD

**Issue by Brandons404** [shelljs/shelljs#1040] opened 2021-07-16 22:11 UTC
### Node version (or tell us if you're using electron or some other framework):
v16.4.2 on NWJS
### ShellJS version (the most recent version/Github branch you see the bug on):
0.8.4
### Operating system:
windows
### Description of the bug:
Any time I run shell.exec() with any argument at all, I get a "no such file or directory" error, regardless of argument passed.

The one I am currently testing with is "echo test", which works in a stand-alone command prompt, git bash, and powershell window. 

I should also mention every other function in the library works just fine.

I'm no javascript expert by any means, but I did my best to find out what I can about the error. 

If I open my AppData/Temp directory, a "shelljs_" file is created, but the characters at the end dont match what is in the error, almost as if its creating a file and trying to access a different one than the one created. 

console error: 
![image](https://user-images.githubusercontent.com/43156510/126014119-a6ff8b63-0ce5-4b2d-8c1e-8a382089d136.png)

actual shell_ file in Temp: 
![image](https://user-images.githubusercontent.com/43156510/126014153-40e92e57-2176-4b29-87a4-b3e1d98e7d41.png)

The documentation says you can optionally pass the path to the shell executable, which yields the same result.

### Example ShellJS command to reproduce the error:

```javascript
const shell = require("shelljs");

shell.exec("echo test");
```

**Comment by pranshu667** [comment] 2021-09-10 21:10
Are you running the above code in browser ?

**Comment by Brandons404** [comment] 2021-09-10 21:39
> 
> 
> Are you running the above code in browser ?

No, this is an NWJS application. This code is running in node

**Comment by nfischer** [comment] 2021-09-11 02:09
Dupe of issue #1024?

**Closed by nfischer** 2021-09-11 02:09 UTC
Labels: duplicate
