### ISSUE TITLE
console.log.apply throwing TypeError: Illegal Invocation

### ISSUE THREAD

**Issue by anoopelias** [shelljs/shelljs#255] opened 2015-11-30 17:44 UTC
I am trying to test pdf.js in [iron-node](https://s-a.github.io/iron-node/) (Electron) and is getting the below error.

	TypeError: Illegal invocation
	    at _echo (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/src/echo.js:17:15)
	    at Function.target.browsertest (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/make.js:1214:3)
	    at Object.global.target.(anonymous function) [as browsertest] (/Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:28:26)
	    at /Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:38:27
	    at Array.forEach (native)
	    at /Users/anoopelias/Workspace/JavaScript/Mozilla/pdfjs/pdf.js/node_modules/shelljs/make.js:36:10

Dug through it and then reached [this line](https://github.com/shelljs/shelljs/blob/561b1ea99ce5bebde07bc70342a8d1cc59279ea0/src/echo.js#L17) in shelljs,

It seems this type of usage of `console.log.apply` may not work everywhere. See relevant StackOverflow [link](http://stackoverflow.com/questions/8159233/typeerror-illegal-invocation-on-console-log-apply).

One more occurrence of the same [here](https://github.com/shelljs/shelljs/blob/e5c26fdaa33ec5f87b55698d6bbb10bb0967eab5/src/common.js#L24),

**Comment by ariporad** [comment] 2016-01-08 02:13
Hmm... This does seem like a bug. I'll send a PR.

**Comment by nfischer** [comment] 2016-01-08 05:54
Possibly a duplicate of #220

**Closed** 2016-01-15 05:04 UTC
Labels: fix
