### ISSUE TITLE
mv does not work with mounted network drives

### ISSUE THREAD

**Issue by jraede** [shelljs/shelljs#191] opened 2015-02-26 16:11 UTC
When I try to run `shelljs.mv(from, to)` where `from` is on the main HD and `to` is on a mounted network drive, I get the following error:

`EXDEV, cross-device link not permitted`

This works fine with `fs.renameSync` and the `mv` library from npm.

**Comment by tivac** [comment] 2015-02-27 00:30
This is a dupe of https://github.com/arturadib/shelljs/issues/1, I've got a PR for it here: https://github.com/arturadib/shelljs/pull/187

**Comment by ariporad** [comment] 2016-01-24 19:51
Closing, as it's a duplicate of #1.

**Closed** 2016-01-24 19:51 UTC
Labels: duplicate
