### ISSUE TITLE
Show `docker exec` output

### ISSUE THREAD

**Issue by whitecolor** [shelljs/shelljs#695] opened 2017-03-25 11:54 UTC
### Node version (or tell us if you're using electron or some other framework):
v6.10.1
### ShellJS version (the most recent version/Github branch you see the bug on):
zsh
### Operating system:
Windows 10/WSL (Ubuntu Linux)

This is a question. I'm trying to run using shell `docker-compose exec [service] bash`
Inner bash prompt of the container opens, but not command output is seen. 
Any advice how to make output of when inside the docker container?

If just run this command from linux bash (not sheljs) ofcource it works fine.

**Comment by whitecolor** [comment] 2017-03-25 20:16
standard `exec` from `child_process` works, so it should be no problem to fix it in shelljs.

**Comment by nfischer** [comment] 2017-03-29 03:53
If `child_process` works for you, use that.

This actually isn't trivial to fix, but will hopefully be fixed by a new API planned for ShellJS v0.8.

Marking as a duplicate of #680

**Closed by nfischer** 2017-03-29 03:53 UTC
Labels: duplicate
