### ISSUE TITLE
`exec` doesn't work like other commands, specifically `cd`

### ISSUE THREAD

**Issue by amacfie** [shelljs/shelljs#701] opened 2017-04-05 03:16 UTC
### Node version (or tell us if you're using electron or some other framework):
6.10.1

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.7

### Operating system:
Ubuntu 16.04

### Description of the bug:
What I'd expect is for `exec` to always be equivalent to the special purpose commands. But as the example below shows, it's not. I found this confusing. Maybe this should be noted in the docs at least?

### Example ShellJS command to reproduce the error:

```javascript
#!/usr/bin/shjs
require('shelljs/global');

// creates `test.txt` in `./dir1/`
cd('dir1/');
exec('echo "test" > test.txt');
cd('../');

// creates `test.txt` in `./`
exec('cd dir1/');
exec('echo "test" > test.txt');
exec('cd ../');
```

**Comment by nfischer** [comment] 2017-04-05 04:25
Duplicate of #496

`exec` runs in a separate process, which makes things like `cd`, `set`, and other environment-modifying commands infeasible. Do you have a suggestion for how we might make this clearer? 😄 

For what it's worth, I added a quick note in the README about it running inside a separate shell:

> Not seeing the behavior you want? exec() runs everything through sh by default (or cmd.exe on Windows), which differs from bash. If you need bash-specific behavior, try out the {shell: 'path/to/bash'} option.

**Closed** 2017-04-10 02:04 UTC
Labels: duplicate
