### ISSUE TITLE
Feature request: Add "shelljs.unlink"

### ISSUE THREAD

**Issue by matthew-dean** [shelljs/shelljs#519] opened 2016-09-23 23:17 UTC
On my Mac (macOS Sierra) `shelljs.rm('/symlink/dir')` of a symlink causes a "permission denied" error, but `shelljs.exec('unlink /symlink/dir')` works fine. Just thinking you could add `unlink()` for symmetry to `ln()`.

**Comment by nfischer** [comment] 2016-09-24 07:09
@matthew-dean I don't have a whole lot of time for the project right now, but you're welcome to try to write up a pull request :smile: Or if you're ambitious, you can make a [ShellJS plugin](https://github.com/shelljs/shelljs/wiki/Using-ShellJS-Plugins). I'll be happy to answer questions for writing the plugin, just ping me on here or [on gitter](https://gitter.im/shelljs/shelljs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!

**Comment by hzlmn** [comment] 2016-09-25 13:08
@matthew-dean  Can you provide repro case, it works fine for me (macOS Sierra as well)?

**Comment by nfischer** [comment] 2016-10-10 05:18
@matthew-dean is this still an issue, or can we close this? If there's a particular file for which this is inconsistent, let us know and perhaps we can find a way to fix it.

**Comment by nfischer** [comment] 2016-10-28 08:13
Closing this due to lack of activity. @matthew-dean if this is still an issue, please ping this thread.

**Comment by mnasyrov** [comment] 2016-12-07 03:27
Faced with this issue on macOS Sierra too (shelljs 0.7.5, shx 0.1.4).

**Comment by nfischer** [comment] 2016-12-07 03:41
Please post the full command you used (actual file paths)

**Comment by mnasyrov** [comment] 2016-12-07 03:59
I run it from my package.json. Below is a similar script which makes the same effect:
```json
{
  "name": "linktest",
  "version": "0.0.1",
  "private": true,
  "devDependencies": {
    "npm-run-all": "3.1.2",
    "shx": "0.1.4",
    "shelljs": "0.7.5"
  },
  "scripts": {
    "test": "npm-run-all -s test:*",
    "test:makedir": "shx mkdir ./dir",
    "test:link": "shx ln -sf $(pwd)/dir ./dir/__dir__",
    "test:unlink": "shx rm ./dir/__dir__"
  }
}
```

It produces a following output:
```
mnasyrov@mn-book:~/dev/linktest $ npm test

> linktest@0.0.1 test /Users/mnasyrov/dev/linktest
> npm-run-all -s test:*


> linktest@0.0.1 test:makedir /Users/mnasyrov/dev/linktest
> shx mkdir ./dir


> linktest@0.0.1 test:link /Users/mnasyrov/dev/linktest
> shx ln -sf $(pwd)/dir ./dir/__dir__


> linktest@0.0.1 test:unlink /Users/mnasyrov/dev/linktest
> shx rm ./dir/__dir__

rm: permission denied: ./dir/__dir__
```

**Comment by nfischer** [comment] 2016-12-07 20:11
@mnasyrov thanks for the follow up. I'll try to reproduce on Linux when I get the chance.

@freitagbr will you have a chance to try to reproduce this on Sierra?

We'll have to close this again if we can't reproduce.

**Comment by freitagbr** [comment] 2016-12-08 04:38
I was able to reproduce this on El Capitan (10.11.6). Exact steps to reproduce (from the repo root):
```
$  mkdir symlink
$ ln -s ../test symlink/dir
$ node
> require('./global')
{}
> rm('symlink/dir')
rm: permission denied: symlink/dir
{ [String: '']
  stdout: '',
  stderr: 'rm: permission denied: symlink/dir',
  code: 1,
  cat: [Function: bound ],
  head: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  uniq: [Function: bound ],
  grep: [Function: bound ],
  exec: [Function: bound ] }
>
```

**Comment by nfischer** [comment] 2016-12-08 04:45
@freitagbr is this the same behavior as unix `rm`? Do we need a new `unlink` command, or is this a bug in the `rm()` function?

**Comment by freitagbr** [comment] 2016-12-08 04:52
I believe it's because `rm` internally treats symlinks and files the same way, even though symlinks can be links to directories. This is not the correct behavior. I think it should treat files, directories, and symlinks all separately.

**Closed** 2016-12-09 07:45 UTC
