### ISSUE TITLE
error with bundled (esbuild) code: cannot find module ./src/cat.js

### ISSUE THREAD

**Issue by noahehall** [shelljs/shelljs#1047] opened 2021-10-06 01:36 UTC
I believe its an issue with how default cmds are required ; and later interpreted by esbuild
@see https://esbuild.github.io/api/#non-analyzable-imports

sorry i dont have time to fix :(

![image](https://user-images.githubusercontent.com/10324554/136126899-31d1a9d3-d026-4bb4-8828-ffa462244f97.png)

![image](https://user-images.githubusercontent.com/10324554/136129197-4661b3db-328b-4d54-b51a-7d5a903925f8.png)

**Comment by nfischer** [comment] 2021-12-08 04:49
Looks like a duplicate of issue #962. This is a bug which will need to be addressed by your bundler. I believe ShellJS is written in a reasonable manner.

**Closed by nfischer** 2021-12-08 04:49 UTC
