### ISSUE TITLE
exec command hanging when pipe empty to `awk`

### ISSUE THREAD

**Issue by Secbone** [shelljs/shelljs#718] opened 2017-05-05 13:08 UTC
exec `awk` command will hang on when the pre-command pipe empty.

```javascript
shell.exec('echo 1 > /dev/null').exec('awk {print}')
```

**Comment by nfischer** [comment] 2017-05-06 01:52
I'll see if I can investigate over the weekend

**Comment by nfischer** [comment] 2017-05-14 23:16
This is related to #551. In both issues, the stdin to the second command is empty. When the second command is something like `grep()`, it will claim that it was provided no input and terminate. In the case of `exec()`, the awk command inside will hang forever waiting for input.

**Comment by nfischer** [comment] 2018-06-26 07:33
Marking this as a duplicate of #551.

**Closed by nfischer** 2018-06-26 07:33 UTC
Labels: duplicate, fix
