### ISSUE TITLE
Create isolated shells

### ISSUE THREAD

**Issue by joviwap** [shelljs/shelljs#261] opened 2015-12-17 18:23 UTC
This is more a question than an issue.

I would like to know if it's possible to create new instances of shelljs in order to have different execution flows. I am creating a bunch of scripts and I would like all the to run at the same time but I am having issues to keep the path stable when to scripts are navigating throw the folders al the same time:

* Script one: 
shell.cd("folder1")
shell.exec(command11)
shell.exec(command12)

* Script two:
shell.cd("folder2")
shell.exec(command2)

lets suppose the script "one" starts before than the "two" and right after starts the other one. What is happening to me is: "command12" is being executed on the "forder2".

How can i solve this issue?
Thank you

**Comment by nfischer** [comment] 2015-12-28 09:08
Could you give an example of how you're executing these scripts? I'm trying to reproduce the bug, but haven't been able to do so:

```Bash
$ shjs test1.js & shjs test2.js
```

test1.js:

```Javascript
shell = require('shelljs');
shell.cd('foo/');
shell.exec('pwd');
shell.cd('..');
```

test2.js:

```Javascript
shell = require('shelljs');
shell.cd('bar/');
shell.exec('ls');
shell.cd('..');
```

How can I change this so that I see the behavior you're seeing?

**Comment by nfischer** [comment] 2016-02-09 07:42
@joviwap I'm pinging this to see if this is still an issue. Could you try this out with the new version, v0.6?

**Comment by joviwap** [comment] 2016-02-10 20:24
Tomorrow I'll try it

**Comment by nfischer** [comment] 2016-02-10 21:10
Ok great! Thanks

**Comment by despairblue** [comment] 2016-03-08 17:05
@nfischer [this](https://gist.github.com/despairblue/cedee6af9c0c1e2b69f9) is probably what he means. And I'd love this as well since I'd like to use it as a way easier way to manipulate files than the stock `fs` module.

Also this makes it impossible to use shelljs in a package. Since since npm@3 multiple packages may use the same shelljs instance :cry:

**Comment by nfischer** [comment] 2016-03-08 17:49
@despairblue what is the desired output from your example? Thanks for providing an example.

**Comment by despairblue** [comment] 2016-03-08 17:58
Thanks for the quick reply.

Well the input would have to be changed
```js
const shelljs = require('shelljs')
const s = shelljs() // an instance that does not share `pwd` with any other instance or the global object
```

Expected output:
```shell
/path/to/project
/path/to/project
```

Actual output without instanciation:
```shell
/path/to/project
/path/to/home
```

**Comment by nfischer** [comment] 2016-03-08 18:02
What if you didn't use shelljs? If you changed pwd to `process.cwd()` and cd to `process.chdir()`, would you still expect to see the same output?

**Comment by despairblue** [comment] 2016-03-08 18:25
Nope, since `process` refers to the same node instance in every module.
I'd like think of `shelljs`-instances as:
* tabs (`shelljs` instances) in a terminal emulator (node instance)
* buffer/windows (`shelljs` instances) in a screen/tmux instance (node instance)
* TTYs (`shelljs` instances) on a linux machine (node instance)

> <small> `shelljs` and node added to the comparison to make a point, not to say that node relates in any way to these, architecture-wise or otherwise</small>

Though I just realized, that `shelljs` doesn't actually manage the `pwd` itself, but changes it on process.

---

I see that it would be hard to change this, but I still think that `shelljs` would be a nice alternative to things like `fs` or `fs-extra`, instead of just using it for writing one-of scripts. Don't you think?

**Comment by nfischer** [comment] 2016-03-08 19:13
I think the current behavior is most intuitive. This is exactly how bash would behave if you replace "require" with "source".

If you need to isolate two scripts, do it in separate processes (that's how bash does it). I think we'd just be limiting ourselves to make that the default behavior.

What prevents you from running cat, rm, cp, etc. as "fs-extra" the way things work? Those don't modify the current process or environment.

**Comment by despairblue** [comment] 2016-03-08 20:40
Ok, probably that came across wrong. I don't want to change the default behaviour. I want to discuss the possibility to implement something to make local instances of shelljs.

> If you need to isolate two scripts, do it in separate processes (that's how bash does it).

That's where I was going with my disclaimer. I'd rather stay in the same node process and have different working directories, instead of spawning another process from node and reading it's STDIN, which would work (since I'd be using another process which can have another pwd), but would be more cumbersome to implement.

I think we're talking past each other. You're thinking that it wouldn't make sense for one process to have multiple pwds, right?
What I'm suggesting is not having a node process with multiple pwds, I think I'm suggesting to emulate pwd for all methods.
I'd think of it like using a jQuery selector. jQuery wraps the nodes I selected and I can keep this jQuery instance around and chain methods onto it and they will only be applied to the selected nodes.

I hope that clarifies what I tried to say :confused: 


If it is out of scope or you deem it not useful, that's fine with me. That would be a good opportunity to close this issue :smiley:

I might have a look at the source and see how difficult it would be to implement.

PS: using fs-extra would mean to either use a differen interface or renaming and/or wrapping some functions, possibly even implementing some of them entirely. I do like the bash-like interface shelljs has, it's just so easy to reason about if you're using a shell the entire day.

**Comment by nfischer** [comment] 2016-03-08 20:53
I think I see where you're going now. To me, it sounds very error prone to fake the cwd, and I don't see much use case for it. It's nice if you want to isolate changes to state, but I think sometimes people want those changes to state to persist.

This reminds me of an experimental JavaScript extension called "Worlds," where changes to state can be isolated in a "world" (they don't affect the parent process, and then later committed or discarded. So I definitely think this is a cool idea :+1:

I'm not sure if this is something as useful to shelljs, since the whole thing is kind of about changing state (remove files, create files, change directory, etc).

To modify shelljs to isolate changes, we would have to conform to the rules:

 1. Don't modify the file system
 2. Don't change directory (or restore those changes)
 3. Don't modify process.env (or restore those changes)

It might be worth it to make a separate module for running shelljs in a non-state-modifying way, until committed. That might be an interesting thought experiment, and I think would solve your problem. What do you think of that?

**Comment by ariporad** [comment] 2016-03-09 01:00
@nfischer: This also is related to my crazy idea of sync-ifying things by having a child process.

**Comment by nfischer** [comment] 2016-03-09 01:40
@ariporad That's similar to how real shells work (except they don't re-implement all the basic utilities). The tradeoffs are, as I see it:

Reasons to do everything in a child process:

 - Changes in state won't affect the parent as much (but the file system can still be affected!)

Reasons to keep things as is:

 - We're now *able* to change state (`cd()` would be impossible any other way)
 - It's faster: we never have to make the `fork()` or `execvp()` system calls underneath our code. Everything runs in one process, so there's no overhead (which is a reason why shelljs sometimes out-performs bash)
 - Less error prone. It's way easier to write synchronous code as synchronous code, rather than to write it as async code and force it to be synchronous by writing to and reading from a file on the file system. This sounds a lot like our `shell.exec()` function for node `v0.10`. Yeah, it works. But keep in mind, we use `execSync()` whenever it's available, and for good reason.

As you can tell, I'm pretty biased. I'm sure I've missed something in favor of the child-process idea, so please chime in with its other benefits. My main concerns are that it would overly complicate something that's already very simple and works very well.

**Comment by ariporad** [comment] 2016-03-10 00:22
@nfischer: We would have to special-case `cd`. I think it could be implemented easily, and it's probably going to be a lot easier to write async code, as that's really what node was designed for.

**Comment by nfischer** [comment] 2016-03-10 00:30
@ariporad that would be a fairly big breaking change, and for what benefit? The whole point of `cd()` is to have side-effects, and now we'd be taking those away?

If you want to write a module that can `cd` places without affecting other modules, do this:

```javascript
var oldDir = pwd();
cd foo/bar/ // go anywhere
// do stuff
cd(oldDir);
// and now we're done
```

**Comment by ariporad** [comment] 2016-03-10 00:35
@nfischer: That isn't what I was saying. What I was suggesting was this.

1. Reimplement every function as fully async.
2. For every async function, run it normally.
3. For every sync function, (except `cd`), we use something similar to the current `exec` implementation, and we use a subprocess to syncify the async version.
4. This would allow easy implementation of this issue, just run async commands and cd in the subprocess too.

**Comment by ariporad** [comment] 2016-03-10 00:36
Also, API idea:

```javascript
var shell = require('shelljs');
var shell2 = new shell.Shell();

shell.pwd(); // /foo/bar
shell2.pwd(); // /foo/bar

shell.cd('baz');

shell.pwd(); // /foo/bar/baz
shell2.pwd(); // /foo/bar
```

**Comment by nfischer** [comment] 2016-03-10 00:46
@ariporad I see what you mean now. Let's continue this conversation on a new thread though, because this is pretty off-topic.

**Comment by despairblue** [comment] 2016-03-10 07:40
@ariporad that's exactly what I would like to have, only that I exported a Factory Function that also included (should have mentioned that) the methods that mutate the node process:

```js
// shelljs
'use strict'

const shellFactory = (options) => {
  // return an instance

  // `pwd` is stored in a local variable
  // `cd` uses `path.resolve` to resolve to the new absolute current working dir and stores it in that local var
  // all other methods use `path.resolve(local.pwd, ...)`
}

Object.assign(shellFactory, {
  // all global methods
})

module.exports = exports = shellFactory
```

That way you can either use shelljs as before or instantiate multiple instances:
```js
var shell = require('shelljs');
var shell2 = shell({fatal: true});

shell.pwd(); // /foo/bar
shell2.pwd(); // /foo/bar

shell.cd('baz');

shell.pwd(); // /foo/bar/baz
shell2.pwd(); // /foo/bar
```

That's what I had in mind, though it does nothing to suffice the async use case.

**Comment by nfischer** [comment] 2016-03-10 23:33
I see how the implementation can work.

@despairblue what is the use case for multiple shelljs instances? Each instance could really only save environment (that's just a JS object...) and cwd (that's just a string...). Do you have a real use-case where you're trying to operate on two directories, it must be concurrently, and it's actually advantageous to do it from the current directory of both?

My issue is that I don't see a good notion of this in unix, so I'm hesitant to merge/write features that deviate strongly from unix conventions.

**Comment by ariporad** [comment] 2016-03-11 01:07
@nfischer: What about this:

We can switch to my suggested implementation. This makes it easier to write commands, and we can easily have sync/async versions of everything. Then we can add subshells if needed. (One concern is that there might be a performance hit).

**Comment by nfischer** [comment] 2016-03-11 01:09
@ariporad Feel free to write up a PR.

**Comment by despairblue** [comment] 2016-04-12 14:34
@nfischer I solved my problem by only using absolute paths. Which works perfectly fine. Sometimes it's just hard to see the obvious solution. 😃 

Thanks for all the input.

**Comment by nfischer** [comment] 2016-04-12 16:45
Glad to hear you found a good work around :+1:

**Comment by nfischer** [comment] 2016-07-25 06:33
Is there any further motivation for multiple ShellJS instances? An advantage of only allowing one instance is that it will allow multiple plugins to hook into the same ShellJS instance.

**Comment by despairblue** [comment] 2016-07-29 13:00
I'm fine with closing this issue 👍

**Closed** 2016-07-29 18:10 UTC
Labels: exec, question
