### ISSUE TITLE
wild card characters in filename not working as expected

### ISSUE THREAD

**Issue by vsathyak** [shelljs/shelljs#262] opened 2015-12-21 12:25 UTC
Code snippet
-------------------
if(shell.test('-f', '/Users/test/protractor/MyProject/downloadedFiles/TestFile.csv')){
                shell.echo('File exist');
            } else {
                shell.echo('File not exist');
            }

The above piece of code is working fine since i mentioned the full path of the file but if the filename contains a wildcard character 
eg  /Users/test/protractor/MyProject/downloadedFiles/*.csv

then the script is always failing and prints the else block always..

Please correct me if there is anything wrong with my code..!!

**Comment by nfischer** [comment] 2015-12-29 01:07
What you're trying to do doesn't seem to be very well supported in Bash, so I think you should try a different practice. Here's an example shell script that won't work very well:

```Bash
touch ~/foo ~/bar # make sure there are two or more files
if test -f ~/*; then
  echo "There is a regular file"
else
  echo "There are no regular files"
fi
rm -f ~/foo ~/bar
```

When I run that, I see the following output:

```
./test.sh: line 3: test: too many arguments
There are no regular files
```

The error lies in the fact that the shell expands `*` to an array of files that match it (aka all your files). The issue is that `test -f` only takes one argument. Since the shell doesn't have *good* support for wild cards in this context, I think for now it isn't worth it to support wild cards for `test()` in this project.

**My recommendation** is to use `ls()`:

```Javascript
if (ls('/home/username/*').length > 0) {
  echo('There is a regular file');
} else {
  echo('There are no regular files');
}
```

**Comment by nfischer** [comment] 2016-01-08 21:53
Closing this for now, since this isn't well supported in Bash, and might be difficult to support well in this scenario. Please feel free to ping this thread if you find a better workaroud/solution, or if this is not sufficient for your purposes.

**Closed by nfischer** 2016-01-08 21:53 UTC
