### ISSUE TITLE
Showing npm loading bar and colors on stdout

### ISSUE THREAD

**Issue by calebmer** [shelljs/shelljs#412] opened 2016-03-27 21:57 UTC
I'm using `shelljs` to run npm commands asynchronously like `npm install`. Can I display the `npm` loading bar and colors with `shelljs`? Currently only the raw text is output, so no color and no loading bar.

I'm using `exec` like this:

```js
exec(`npm install "${name}@${version}"`, { async: true }, () => {
  …
})
```

**Comment by ariporad** [comment] 2016-03-27 22:21
Hi @calebmer!

Yes, we know about this issue. However, this is due to the way that we spawn our child processes. Sorry about that.

I'm going to keep this open, because it would be fixed by #402.

**Comment by calebmer** [comment] 2016-03-28 00:00
Thanks, looking forward to see this working 😊

**Comment by nfischer** [comment] 2016-03-28 04:36
Marking this as a duplicate of #242

**Comment by skevy** [comment] 2016-04-02 14:57
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Comment by skevy** [comment] 2016-04-02 14:58
Hey and thanks for reporting this!

There's an awesome place to ask question like this one: [StackOverflow](http://stackoverflow.com/questions/tagged/react-native). It's the best system for Q&A. Many people from the community hang out there and will be able to see your question, you can vote on answers and mark question as answered etc. This lets us keep a list of bug reports and feature requests on github and especially [Product Pains](https://productpains.com/product/react-native/?tab=top) (again, with voting which is really nice).

If you think StackOverflow works for you please consider posting there instead and closing this issue.

I'm posting this here because github issues haven't been working very well for us and because StackOverflow is so much better. Thanks for reading! :)

**Closed** 2016-04-02 16:07 UTC
Labels: duplicate
