### ISSUE TITLE
ShellJS works in Electron in one app, but gives Error 'Unable to find a path to node binary' in another

### ISSUE THREAD

**Issue by bmcgonag** [shelljs/shelljs#704] opened 2017-04-18 01:44 UTC
### Node version (or tell us if you're using electron or some other framework):
Electron 1.6.2 (non-working app installed globally)

Electron 1.4.13 (working app installed as dev dependency for this app only).

I apparently installed Electron locally on one folder, and then globally later.

### ShellJS version (the most recent version/Github branch you see the bug on):
ShellJS 0.7.7 (non-working app)

ShellJS 0.7.5 (working app)

### Operating system:
MacOS and Ubuntu Linux 16.04 LTS

### Description of the bug:
In one setup I'm using ShellJS with no issue running shells.exec() and my command runs fine.

In the new setup I'm using ShellJS with a globally installed Electron, and I get an 'Unable to find a path to node binary' message.  It suggests setting the path manually, but I see some issues with this.  If I distribute the app, this won't work for everyone else, right?

### Example ShellJS command to reproduce the error:
Just pick one.

```javascript

```

**Comment by bmcgonag** [comment] 2017-04-18 01:54
As a follow up.  I uninstalled shelljs 0.7.7 and installed 0.7.5 in it's place, and it's now running the commands just like in my other app. 

Seems to be something that has changed in shells since 0.7.5 that has caused this break.

**Comment by nfischer** [comment] 2017-04-19 06:08
We don't support electron yet. See [this wiki page](https://github.com/shelljs/shelljs/wiki/Electron-compatibility). Do you see this message when invoking non-exec commands?

#636 introduced this. This was intended to give better control for Electron support (e.g. `config.execPath = shell.which('node')` if that's good enough).

If you're interested in electron support, I'll gladly review a pull request.

**Comment by nfischer** [comment] 2017-06-07 04:40
Closing this, because we don't provide electron support. If someone wants to help us out here, we'll gladly revisit this.

**Closed by nfischer** 2017-06-07 04:40 UTC

**Comment by achekulaev** [comment] 2018-02-04 03:56
```
shell.config.execPath = shell.which('node')
shell.exec(...)
```
works just fine. 

I wonder why there is a need to specify this manually if `shell.which` is actually able to find `node` binary, but other that that, it works.

**Comment by nfischer** [comment] 2018-02-04 20:41
> I wonder why there is a need to specify this manually if shell.which is actually able to find node binary, but other that that, it works.

`shell.which('node')` isn't perfect: the node binary might be named `nodejs` (or any name).

I'm not opposed to trying `shell.which()` before throwing an error to the user. Feel free to send a PR.

**Comment by mvkanha** [comment] 2019-02-15 12:55
I had tried with `node` and `nodejs` but both are not working for me in window os
```
var shell = require('shelljs')
console.log("shell.config.execPath",shell.config.execPath) // return null
shell.config.execPath = shell.which('nodejs');
```

**Comment by nfischer** [comment] 2019-02-16 01:10
@mvkanha do you have node installed on your system?

**Comment by mvkanha** [comment] 2019-02-19 05:43
@nfischer  Yes I have installed  node on my system

**Comment by nfischer** [comment] 2019-02-20 16:55
@mvkanha then specify the full path to your installed `node` binary.

**Comment by spiddy** [comment] 2019-06-23 12:33
> I had tried with `node` and `nodejs` but both are not working for me in window os
> 
> ```
> var shell = require('shelljs')
> console.log("shell.config.execPath",shell.config.execPath) // return null
> shell.config.execPath = shell.which('nodejs');
> ```

The following worked for me, since the output is a [ShellString]

[ShellString]: https://github.com/shelljs/shelljs/blob/master/src/which.js#L56

```
    shell.config.execPath = String(shell.which('node'))
```

**Comment by nfischer** [comment] 2019-06-24 18:40
@spiddy I updated the [wiki](https://github.com/shelljs/shelljs/wiki/Electron-compatibility) with a modification of your suggestion (We explicitly support `.toString()`). https://github.com/shelljs/shelljs/issues/704#issuecomment-362937847 is also an option for anyone willing to send a PR.

**Comment by linonetwo** [comment] 2020-01-24 09:54
After bundling, `shell.which('node')` will be undefined, so

`shell.config.execPath = shell.which('node').toString();` won't work.

**Comment by aayusharora** [comment] 2020-09-23 03:20
How can we solve this after bundling?

**Comment by stjava** [comment] 2021-09-09 08:40
I also encountered this problem
