### ISSUE TITLE
Node.js 14.4.0 is not verified. NativeScript CLI might not install or run properly.

### ISSUE THREAD

**Issue by Work90210** [shelljs/shelljs#1000] opened 2020-06-26 15:15 UTC
I get the following errors when I run nativescript sidekick.

at Module.require (internal/modules/cjs/loader.js:1089:19)
at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
at Object.get (internal/modules/cjs/loader.js:837:5)
at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
at Object. (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/toEnd.js:5:8)
at Module._compile (internal/modules/cjs/loader.js:1200:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
at Module.load (internal/modules/cjs/loader.js:1049:32)
at Function.Module._load (internal/modules/cjs/loader.js:937:14)
at Module.require (internal/modules/cjs/loader.js:1089:19)
at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
at Object.get (internal/modules/cjs/loader.js:837:5)
at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
at Object. (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/touch.js:4:8)
at Module._compile (internal/modules/cjs/loader.js:1200:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
at Module.load (internal/modules/cjs/loader.js:1049:32)
at Function.Module._load (internal/modules/cjs/loader.js:937:14)
at Module.require (internal/modules/cjs/loader.js:1089:19)
at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
at Object.get (internal/modules/cjs/loader.js:837:5)
at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/co
[20-06-25 20:58:26.367] Support for Node.js 14.4.0 is not verified. NativeScript CLI might not install or run properly.
[20-06-25 20:58:26.369] (CLI) mmon.js:419:12)
at Object. (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/uniq.js:13:8)
at Module._compile (internal/modules/cjs/loader.js:1200:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
at Module.load (internal/modules/cjs/loader.js:1049:32)
at Function.Module._load (internal/modules/cjs/loader.js:937:14)
at Module.require (internal/modules/cjs/loader.js:1089:19)
at require (internal/modules/cjs/helpers.js:73:18)
(node:8331) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
at Object.get (internal/modules/cjs/loader.js:837:5)
at Object._register [as register] (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/common.js:419:12)
at Object. (/Applications/NativeScript Sidekick.app/Contents/Resources/node_modules/nativescript/node_modules/shelljs/src/which.js:5:8)
at Module._compile (internal/modules/cjs/loader.js:1200:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
at Module.load (internal/modules/cjs/loader.js:1049:32)
at Function.Module._load (internal/modules/cjs/loader.js:937:14)
at Module.require (internal/modules/cjs/loader.js:1089:19)
at require (internal/modules/cjs/helpers.js:73:18)

**Comment by nfischer** [comment] 2020-06-26 16:35
Can you include the following info?

---

### Node version (or tell us if you're using electron or some other framework):

(Could you explain what sidekick is?)

### ShellJS version (the most recent version/Github branch you see the bug on):

### Operating system:

### Example ShellJS command to reproduce the error:

```javascript
// TODO

```

**Comment by Work90210** [comment] 2020-06-26 18:22
@nfischer sorry for being vague.

node v14.4.0
npm v6.14.5

I have nativescript sidekick installed and I get the errors when I open it.

To remake the error run `tns run ios`

**Comment by nfischer** [comment] 2020-06-29 01:28
I think this is a duplicate of https://github.com/NativeScript/nativescript-cli/issues/5335 and #991. Try reinstalling nativescript.

**Closed by nfischer** 2020-06-29 01:28 UTC
