### ISSUE TITLE
grep: option not recognized: l

### ISSUE THREAD

**Issue by davidwilder** [shelljs/shelljs#717] opened 2017-05-04 00:40 UTC
### Node version (or tell us if you're using electron or some other framework):
v6.9.5

### ShellJS version (the most recent version/Github branch you see the bug on):
 v0.7.7

### Operating system:
macOS 10.12.4

### Description of the bug:
Getting this error when trying to use grep -l option. 

> grep: option not recognized: l

### Example ShellJS command to reproduce the error:

```javascript
#! /usr/bin/env node
const shell = require('shelljs');
const fileList = shell.grep('-l', 'angular.module(\'App\').component', '*.js');
```

**Comment by freitagbr** [comment] 2017-05-04 03:37
Hi @davidwilder, I am unable to reproduce this issue with node v6.9.5 and macOS 10.11.6. Could you provide more details about the issue and/or your setup? Thanks!

**Comment by nfischer** [comment] 2017-05-14 23:11
I'm going to close this, since I don't think this is possible. If you can reproduce this, please ping this issue and we can reopen it.

**Closed by nfischer** 2017-05-14 23:11 UTC
